version: '3'

services:

  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}

    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql/

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/crypto-exchange-api
      - ./logs/nginx/:/var/log/nginx:cached
    depends_on:
      - fpm
    ports:
      - "80:80"
    links:
      - fpm

  fpm:
    build:
      context: '.'
      dockerfile: 'docker/fpm/Dockerfile'
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www/crypto-exchange-api:cached
    ports:
      - '9002:9000'
volumes:
  db-data:

